version: 2.1

jobs:
  build_apk:
    machine:
      image: ubuntu-2204:2024.01.2
      
    steps:
      - checkout
      - run:
          name: Install Flutter
          command: |
            git clone https://github.com/flutter/flutter.git -b stable
            echo 'export PATH="$PATH:`pwd`/flutter/bin"' >> $BASH_ENV
            source $BASH_ENV
            flutter doctor
          
      - run:
          name: "Install Java 17"
          command: |
            sudo apt-get update
            sudo apt-get install -y openjdk-17-jdk
      - run:
          name: "Flutter Build APK"
          command: flutter build apk

workflows:
  build:
    jobs:
      - build_apk
         
