version: 2.1

jobs:
  build_apk:
    docker:
      - image: instrumentisto/flutter:latest
      
    steps:
      - checkout    
      - run:
          name: "Install Java 17"
          command: |
            sudo apt-get update
            sudo apt-get install -y openjdk-17-jdk
      - run:
          name: "Flutter Build APK"
          command: flutter build apk

workflows:
  build:
    jobs:
      - build_apk
         
